baseURL = "https://ibrahimstephenson.github.io/"
locale = "en-us"
defaultContentLanguage = "en"
title = "Ibrahim Stephenson"
theme = "dream"

[params]
  author = "Ibrahim Stephenson"
  description = "Power Platform Developer | Content Creator | Chess enthusiast"
  motto = "Power Platform Developer | YouTuber | Chess enthusiast"
  showSummary = true
  avatar = "/logo.png"
  lightTheme = "emerald"
  darkTheme = "forest"
  reorderNavItems = ["about", "posts", "search", "tags", "categories", "linkedin", "github"]

[params.navItems]
  linkedin = { href = "https://www.linkedin.com/in/ibrahimstephenson", target = "_blank", icon = "logo-linkedin", title = "LinkedIn" }
  github = { href = "https://github.com/IbrahimStephenson", target = "_blank", icon = "logo-github", title = "GitHub" }