baseURL = "https://ibrahimstephenson.github.io/"
locale = "en-us"
defaultContentLanguage = "en"
title = "Ibrahim Stephenson"
theme = "dream"
buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Ibrahim Stephenson"
  description = "Power Platform Developer"
  motto = "Welcome to my Mind Palace"
  showSummary = true
  avatar = "/logo.png"
  lightTheme = "emerald"
  darkTheme = "forest"
  noDefaultSummaryCover = true
  reorderNavItems = ["home", "blogs", "library", "about", "search", "linkedin", "github", "email"]

[params.advanced]
  customCSS = ["/css/custom.css"]

[params.navItems]
  home = { href = "/", title = "Home" }
  blogs = { href = "/posts/", title = "Blogs" }
  library = { href = "/library/", title = "Library" }
  linkedin = { href = "https://www.linkedin.com/in/ibrahimstephenson", target = "_blank", icon = "logo-linkedin", title = "LinkedIn" }
  github = { href = "https://github.com/IbrahimStephenson", target = "_blank", icon = "logo-github", title = "GitHub" }
  email = { href = "mailto:Ibrahimstephenson@gmail.com?subject=Portfolio%20Enquiry", icon = "mail", title = "Contact Me" }

[params.book]
  title = "The Poppy War"
  author = "R.F. Kuang"
  note = "Speechless."
  cover = "/images/books/poppy-war.jpg"