baseURL = "https://ibrahimstephenson.github.io/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
locale = "en-us"
defaultContentLanguage = "en"
title = "Ibrahim Stephenson"
theme = "dream"
buildFuture = true

[params]
  author = "Ibrahim Stephenson"
  description = "Power Platform Developer"
  motto = "Welcome to my Mind Palace"
  showSummary = true
  avatar = "/logo.png"
  lightTheme = "emerald"
  darkTheme = "forest"
  noDefaultSummaryCover = true
  reorderNavItems = ["about", "posts", "search", "categories", "linkedin", "github", "email"]

[params.advanced]
  customCSS = ["/css/custom.css"]

[params.navItems]
  linkedin = { href = "https://www.linkedin.com/in/ibrahimstephenson", target = "_blank", icon = "logo-linkedin", title = "LinkedIn" }
  github = { href = "https://github.com/IbrahimStephenson", target = "_blank", icon = "logo-github", title = "GitHub" }
  email = { href = "mailto:Ibrahimstephenson@gmail.com?subject=Portfolio%20Enquiry", icon = "mail", title = "Contact Me" }